// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWorldDropItem(arg1, arg2, arg3, arg4) {
  return window['go']['api']['App']['AddWorldDropItem'](arg1, arg2, arg3, arg4);
}

export function CheckDataUpdate() {
  return window['go']['api']['App']['CheckDataUpdate']();
}

export function DelWorldDropItem(arg1, arg2, arg3) {
  return window['go']['api']['App']['DelWorldDropItem'](arg1, arg2, arg3);
}

export function EquipmentBatchHandle(arg1, arg2) {
  return window['go']['api']['App']['EquipmentBatchHandle'](arg1, arg2);
}

export function ExportFiles(arg1) {
  return window['go']['api']['App']['ExportFiles'](arg1);
}

export function GenBox(arg1) {
  return window['go']['api']['App']['GenBox'](arg1);
}

export function GenRandomBox(arg1) {
  return window['go']['api']['App']['GenRandomBox'](arg1);
}

export function GetClearRewardDrop() {
  return window['go']['api']['App']['GetClearRewardDrop']();
}

export function GetExtraMonsterDrop() {
  return window['go']['api']['App']['GetExtraMonsterDrop']();
}

export function GetFileContent(arg1) {
  return window['go']['api']['App']['GetFileContent'](arg1);
}

export function GetHellDrop() {
  return window['go']['api']['App']['GetHellDrop']();
}

export function GetItemsName(arg1) {
  return window['go']['api']['App']['GetItemsName'](arg1);
}

export function GetJobInfo() {
  return window['go']['api']['App']['GetJobInfo']();
}

export function GetJobSkill(arg1) {
  return window['go']['api']['App']['GetJobSkill'](arg1);
}

export function GetMonsterDrop() {
  return window['go']['api']['App']['GetMonsterDrop']();
}

export function GetSkillDetail(arg1) {
  return window['go']['api']['App']['GetSkillDetail'](arg1);
}

export function GetUserSettings() {
  return window['go']['api']['App']['GetUserSettings']();
}

export function GetWorldDropData(arg1) {
  return window['go']['api']['App']['GetWorldDropData'](arg1);
}

export function LoadData(arg1) {
  return window['go']['api']['App']['LoadData'](arg1);
}

export function QueryEquipments(arg1) {
  return window['go']['api']['App']['QueryEquipments'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['api']['App']['SaveFile'](arg1, arg2);
}

export function SaveWorldDropData() {
  return window['go']['api']['App']['SaveWorldDropData']();
}

export function SearchByName(arg1) {
  return window['go']['api']['App']['SearchByName'](arg1);
}

export function SetClearRewardDrop(arg1) {
  return window['go']['api']['App']['SetClearRewardDrop'](arg1);
}

export function SetHellDrop(arg1, arg2) {
  return window['go']['api']['App']['SetHellDrop'](arg1, arg2);
}

export function SetMonsterDrop(arg1) {
  return window['go']['api']['App']['SetMonsterDrop'](arg1);
}

export function SetMonsterExtraDrop(arg1) {
  return window['go']['api']['App']['SetMonsterExtraDrop'](arg1);
}

export function SetSkillData(arg1, arg2, arg3, arg4) {
  return window['go']['api']['App']['SetSkillData'](arg1, arg2, arg3, arg4);
}

export function SetUserSettings(arg1) {
  return window['go']['api']['App']['SetUserSettings'](arg1);
}
