// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data_loader} from '../models';
import {script} from '../models';
import {model} from '../models';
import {api} from '../models';
import {setting} from '../models';
import {world_drop} from '../models';

export function AddWorldDropItem(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function CheckDataUpdate():Promise<Array<data_loader.CheckUpdateResult>>;

export function DelWorldDropItem(arg1:number,arg2:number,arg3:Array<number>):Promise<void>;

export function EquipmentBatchHandle(arg1:Array<number>,arg2:Array<script.Action>):Promise<void>;

export function ExportFiles(arg1:Array<string>):Promise<void>;

export function GetClearRewardDrop():Promise<Array<number>>;

export function GetExtraMonsterDrop():Promise<Array<any>>;

export function GetFileContent(arg1:string):Promise<string>;

export function GetHellDrop():Promise<Array<number>>;

export function GetItemsName(arg1:Array<number>):Promise<{[key: number]: string}>;

export function GetJobSkill(arg1:number):Promise<Array<model.Skill>>;

export function GetMonsterDrop():Promise<Array<any>>;

export function GetSkillDetail(arg1:number):Promise<api.SkillData>;

export function GetUserSettings():Promise<setting.SettingStruct>;

export function GetWorldDropData(arg1:number):Promise<Array<world_drop.WorldDropItem>>;

export function LoadData(arg1:Array<string>):Promise<void>;

export function QueryEquipments(arg1:api.EquQueryCond):Promise<Array<model.Equipment>>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveWorldDropData():Promise<void>;

export function SetClearRewardDrop(arg1:Array<number>):Promise<void>;

export function SetHellDrop(arg1:Array<number>,arg2:Array<number>):Promise<void>;

export function SetMonsterDrop(arg1:Array<any>):Promise<void>;

export function SetMonsterExtraDrop(arg1:Array<any>):Promise<void>;

export function SetSkillData(arg1:number,arg2:Array<number>,arg3:Array<any>,arg4:boolean):Promise<void>;

export function SetUserSettings(arg1:setting.SettingStruct):Promise<void>;
