// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {data_loader} from '../models';
import {script} from '../models';
import {box} from '../models';
import {proto} from '../models';
import {api} from '../models';
import {setting} from '../models';
import {world_drop} from '../models';

export function AddCustomAttrTmpl(arg1:model.CustomAttrTmpl):Promise<void>;

export function AddWorldDropItem(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function CheckDataUpdate():Promise<Array<data_loader.CheckUpdateResult>>;

export function DelWorldDropItem(arg1:number,arg2:number,arg3:Array<number>):Promise<void>;

export function DeleteCustomAttrTmpl(arg1:number):Promise<void>;

export function EquipmentBatchHandle(arg1:Array<number>,arg2:Array<script.Action>):Promise<void>;

export function ExportFiles(arg1:Array<string>):Promise<void>;

export function GenBox(arg1:box.BoxParams):Promise<string>;

export function GenRandomBox(arg1:box.BoxParams):Promise<string>;

export function GetBreathData(arg1:number):Promise<proto.BreathData>;

export function GetClearRewardDrop():Promise<Array<number>>;

export function GetCustomAttrTmpls():Promise<Array<model.CustomAttrTmpl>>;

export function GetExtraMonsterDrop():Promise<Array<any>>;

export function GetFileContent(arg1:string):Promise<string>;

export function GetHellDrop():Promise<Array<number>>;

export function GetItemsName(arg1:Array<number>):Promise<{[key: number]: string}>;

export function GetJobInfo():Promise<Array<model.Job>>;

export function GetJobSkill(arg1:number):Promise<Array<model.Skill>>;

export function GetMonsterDrop():Promise<Array<any>>;

export function GetSkillDetail(arg1:number):Promise<api.SkillData>;

export function GetUpgradeData(arg1:number):Promise<Array<proto.UpgradeItem>>;

export function GetUserSettings():Promise<setting.SettingStruct>;

export function GetWorldDropData(arg1:number):Promise<Array<world_drop.WorldDropItem>>;

export function LoadData(arg1:Array<string>):Promise<void>;

export function QueryEquipments(arg1:api.EquQueryCond):Promise<Array<model.Equipment>>;

export function ReloadBreath(arg1:number):Promise<proto.BreathData>;

export function SaveBreath(arg1:number):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveUpgradeData(arg1:number):Promise<void>;

export function SaveWorldDropData():Promise<void>;

export function SearchByName(arg1:string):Promise<Array<api.SearchResult>>;

export function SetBreathBaseData(arg1:number,arg2:number,arg3:number):Promise<void>;

export function SetBreathSkills(arg1:number,arg2:number,arg3:number,arg4:string,arg5:Array<proto.BreathCheckSkillItem>):Promise<void>;

export function SetClearRewardDrop(arg1:Array<number>):Promise<void>;

export function SetHellDrop(arg1:Array<number>,arg2:Array<number>):Promise<void>;

export function SetMonsterDrop(arg1:Array<any>):Promise<void>;

export function SetMonsterExtraDrop(arg1:Array<any>):Promise<void>;

export function SetSkillData(arg1:number,arg2:Array<number>,arg3:Array<any>,arg4:boolean):Promise<void>;

export function SetUpgradeItem(arg1:number,arg2:Array<proto.UpgradeItem>):Promise<void>;

export function SetUserSettings(arg1:setting.SettingStruct):Promise<void>;

export function UpdateCustomAttrTmpl(arg1:model.CustomAttrTmpl):Promise<void>;
